name: 11ZHMolLigGraph
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.18
  - cudatoolkit=10.2
  - pip
  - pip:
    - h5py==3.10.0
    - scipy==1.10.1
    - tqdm==4.66.1
    - pandas==2.0.3
    - googledrivedownloader==0.4
    - torch==1.7.1+cu101 --find-links https://download.pytorch.org/whl/torch_stable.html
    - torchvision==0.8.2+cu101 --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch-scatter -f https://data.pyg.org/whl/torch-1.7.1+cu101.html
    - torch-sparse -f https://data.pyg.org/whl/torch-1.7.1+cu101.html
    - torch-cluster -f https://data.pyg.org/whl/torch-1.7.1+cu101.html
    - torch-spline-conv -f https://data.pyg.org/whl/torch-1.7.1+cu101.html
    - torch-geometric==1.6.3
